# Generated by Django 3.1.6 on 2021-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210428_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
