# Generated by Django 3.1.6 on 2021-04-27 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210428_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='Price',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='Release',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date released'),
        ),
    ]
